M48
; DRILL file {KiCad 7.0.1} date Mon Oct  9 09:12:25 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-09T09:12:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X125.984Y-86.868
X125.984Y-119.38
X182.118Y-86.868
X182.118Y-119.38
T0
M30
